### ISSUE TITLE
Addon doesn't send emails

### ISSUE THREAD

**Issue by micheldejoode** [Markei/Google-Forms-Confirmation-and-thank-you-mailer#2]
Hi, I've tested your addon, but I can't get it to send emails. I've selected the "emailadress" placeholder from the form, so I don't understand what's going wrong here. Any ideas?

Greetings, 
Michel

**Comment by maartendekeizer** [comment]
Hi,
First create a form field (type: short answer) where the user can enter his email address. Add a validation constraint for email addresses to be sure the user fills a valid address.
Next add the add on and go to Setup.
In the "Sent e-mail to address in the following field"-field select the just created field. Keep CC blank, set subject to "test" and message to "test".
Save the add on.
Go to the preview (or live version of your form) and fill in. Use a different e-mail than you own Gmail.

**Comment by micheldejoode** [comment]
Hi Maarten,

I see where the problem is, I used my own emailadres to test it, and so 
it didn't send the email. Thanks!

Greetings,
Michel

Op 6-11-2016 om 16:43 schreef Maarten de Keizer:
